feat: use the dominant color of a user's avatar as the color of his/her racing bar
hypertrons/hypertrons-crx pull request #727
Opened 2023-08-26 08:43 UTC by tyn1998

## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #723 

## Details

<img width="1549" alt="image" src="https://github.com/hypertrons/hypertrons-crx/assets/32434520/4bd4fb9f-bc1e-4276-a748-1710e388f6cd">

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

2023-08-26 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=727) before we can accept your contribution.<br/><hr/>**Bach** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hypertrons/hypertrons-crx?pullRequest=727) it.</sub>

2023-08-26 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=727) before we can accept your contribution.<br/><hr/>**Bach** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hypertrons/hypertrons-crx?pullRequest=727) it.</sub>

2023-08-26 08:51 UTC, tyn1998 commented
Loading images and extracting colors need time, which causes the animation to freeze for a while. I think all avatars should be loaded and processed before the animation starts.

2023-08-31 19:21 UTC, TieWay59 commented on src/pages/ContentScripts/features/repo-activity-racing-bar/AvatarColorStore.ts
> +          )
虽然这里采用了缓存，但这里实际的性能瓶颈应该在于单线程等待多个图片下载+parse，当作同步任务这样造成了卡顿。比较合理的做法应该是立即在缓存里设置一个默认颜色，再注册异步事件去下载+parse在回调时永久性更新的缓存颜色。保证竞赛图更新的时候立即获取到默认值，假如下载顺利-下次update的时候能够获取到真实的颜色。但是在当前的框架下，看起来改动有所难度。

2023-08-31 19:32 UTC, TieWay59 commented
> Loading images and extracting colors need time, which causes the animation to freeze for a while. I think all avatars should be loaded and processed before the animation starts.

预处理确实可以绕过现有问题，但假如预处理如果还是同步地处理，只是把延迟时间转移到了动画启动之前。压测一个1000人的仓库估计够呛，（且不提缓存收缩是否值得考虑）。

Preprocessing may solve the current issue, but if it is done synchronously, it only shifts the delay to before the animation begins. I doubt your system can handle a repo of 1000 people with this approach.

2023-08-31 19:42 UTC, TieWay59 requested changes

2023-08-31 19:42 UTC, TieWay59 commented on src/pages/ContentScripts/features/repo-activity-racing-bar/AvatarColorStore.ts
> +          )
我甚至觉得更好的该是：AvatarColorStore 在回调中直接修改 bar 的颜色。updateMonth 只在首次发现没颜色的时候向AvatarColorStore 发起颜色请求。

2023-09-17 06:07 UTC, tyn1998 commented
@TieWay59 thanks for reviewing the code ❤️ . I have improved the preload and cache mechanism, as well as the UI experience :)

This PR is ready, request for your review ❤️  @lhbvvvvv @wxharry

2023-09-19 13:50 UTC, tyn1998 commented
Hello guys @zhaosj975 @Tenth-crew @wangyantong2000, would you like to `gh pr checkout 727` (install `gh` first) this PR branch and have a test in your machine?

Reference: https://github.com/hypertrons/hypertrons-crx#contributing

2023-09-19 15:06 UTC, Tenth-crew commented
好的师兄，之后会尝试

> Hello guys @zhaosj975 @Tenth-crew @wangyantong2000, would you like to `gh pr checkout 727` (install `gh` first) this PR branch and have a test in your machines? Welcome to your snapshots or recordings.
> 
> Reference: https://github.com/hypertrons/hypertrons-crx#contributing

2023-09-19 16:02 UTC, tyn1998 commented
@Tenth-crew  Great!

BTW, in this project we use English to communicate with each other so more people abroad can understand and participate in :)

2023-09-20 11:38 UTC, zhaosj975 commented
![image](https://github.com/hypertrons/hypertrons-crx/assets/79428895/4141267e-9980-47ab-8a82-3f0de97ee80c)
so convenient it is!

2023-09-20 11:59 UTC, Tenth-crew commented
![image](https://github.com/hypertrons/hypertrons-crx/assets/68376741/2b79f217-c82a-40f0-9bd0-91904ac168e4)

2023-09-20 12:14 UTC, wangyantong2000 commented
Uploading test.mp4…

2023-09-22 03:24 UTC, lhbvvvvv approved these changes
LGTM! 

/approve

2023-09-22 03:50 UTC, merged