i18n in options.tsx
hypertrons/hypertrons-crx pull request #826
Opened 2024-06-09 03:31 UTC by taketaketakeru

## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([Task1 i18n](https://github.com/hypertrons/hypertrons-crx/issues/805)):

- Task1 i18n

## Details

changes to i18n in hypertrons-crx\src\pages\Options\Options.tsx

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

2024-06-09 03:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=826) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hypertrons/hypertrons-crx?pullRequest=826) before we can accept your contribution.<br/><hr/>**taketaketakeru** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hypertrons/hypertrons-crx?pullRequest=826) it.</sub>

2024-06-12 02:19 UTC, wxharry commented
Hi, sorry for the delay reply. I have gone through your work quickly and looks like everything is on the right track. About your questions, I will reply in the related issue in details. For your current work, (I am not giving reviews, just trying to make your future work easier), we might want to change our message files, maybe change its name to translation.json and simplify its structure as i18next recommended:
``` json
{
  "welcome": "Welcome to React and react-i18next",
  "change_language": "Change Language"
}
```
For sure there will be a lot of changes but feel free to make changes if it is necessary. :)
cc @tyn1998

2024-06-21 13:19 UTC, wxharry commented
Hi, thanks for the contributions. Please feel free to remove code and delete files when working on it. Git keeps the history for us, we can recover anything deleted in the branch. So, if you think such code is no longer needed, delete it instead of commenting it out.

2024-06-22 11:36 UTC, taketaketakeru commented
> Hi, thanks for the contributions. Please feel free to remove code and delete files when working on it. Git keeps the history for us, we can recover anything deleted in the branch. So, if you think such code is no longer needed, delete it instead of commenting it out.

OK ;-)

2024-06-22 17:00 UTC, wxharry commented
Looks like you are having a conflict in this PR, you can look into `git merge` or `git rebase` command to resolve it. Let me know if you have trouble resolving it.

BTW, Don't forget to sign the Contributor License Agreemenet

2024-06-23 06:17 UTC, taketaketakeru commented
> Looks like you are having a conflict in this PR, you can look into `git merge` or `git rebase` command to resolve it. Let me know if you have trouble resolving it.
> 
> BTW, Don't forget to sign the Contributor License Agreemenet

Sorry for the mistakes! :-O  
I was confused before until I found I signed the Contributor License Agreement with an unmatched email address. Then, I resolved the conflict issues and the CLA issues. Now, it seems to look good. 
Please let me know if there is still something wrong. :-D

2024-06-25 02:30 UTC, wxharry commented
> Sorry for the mistakes! :-O

This is not your fault. It is common to have conflicts since others are also working on it.

Is this PR ready to review?

2024-06-25 04:33 UTC, taketaketakeru commented
> 
> This is not your fault. It is common to have conflicts since others are also working on it.
> 
> Is this PR ready to review?

Yes, it's ready for review.  :-D

2024-06-26 13:36 UTC, wxharry requested changes
Nice work! I have left a few comments that will improve your work and understand more about the library. lmk if you have any questions.

2024-06-26 13:36 UTC, wxharry commented on src/pages/ContentScripts/features/repo-networks/view.tsx
> +            {t('global_period')}: {REPO_PERIOD} {t('global_day')}
Can we use [i18next Plurals](https://www.i18next.com/translation-function/plurals) here since `global_day` depends on a variable  `REPO_PERIOD`?

2024-06-26 13:36 UTC, wxharry commented on src/pages/ContentScripts/features/repo-networks/view.tsx
> +            {t('global_period')}: {DEVELOPER_PERIOD} {t('global_day')}
Same here, we can use Plurals

2024-06-26 13:36 UTC, wxharry commented on src/locales/en/translation.json
> +  "contributors_participants_icon": "GitHub repository contributors and participants count over time. And you can zoom in/out on the axes using the mouse scroll wheel.",
These are duplicate. Could you look into [i18n nesting](https://www.i18next.com/translation-function/nesting) to simplify this part?

2024-06-27 10:27 UTC, taketaketakeru commented on src/locales/en/translation.json
> +  "manifest_appDescription": "Hypertrons-crx, tracking, tracing and digging GitHub projects and developers",
OK, I already have them removed.

2024-06-27 11:29 UTC, taketaketakeru commented
> Nice work! I have left a few comments that will improve your work and understand more about the library. lmk if you have any questions.
> 
> Is #804 fixed in this PR? I am still having the issue. (Just asking, this is not mandatory for this branch)

I refined the code according to the review comments.  :-D

As for #804, since I added the `i18n.changeLanguage(options.locale);`  in repo-header-labels\view.tsx as follows,
```
useEffect(() => {
    (async function () {
      setOptions(await optionsStorage.getAll());
      i18n.changeLanguage(options.locale);
    })();
  }, [options.locale]);
```
now it can display the corresponding language correctly under different language settings. 
However, this cannot take effect as soon as changing the language settings. It will only display the correct language **after refreshing the webpage**, unlike the star-button and the fork-button.

I think the reason for this is the repo-head-labels only be loaded once when initing the webpage, so the change of language setting will not take effect immediately since the repo-head-labels won't be reloaded.  Even if I change the code as follows (add the options.locale in ** **), it won't help for the same reason. (I’m not pretty sure about the reason).
```
useEffect(() => {
    const placeholderElement = $('<div class="NativePopover" />').appendTo('body')[0];
    render(
      <>
        <NativePopover anchor={$('#activity-header-label')} width={280} arrowPosition="top-middle">
              ......
        </NativePopover>
      </>,
      placeholderElement
    );
  }, [**options.locale**]);
```

Since I'm not quite familiar with React, I don't know the exact reason for this and where to change to fix this problem. If you give me a more specific reason for the bug, I would like to try to fix the issue! 🧐
Or is the current solution as adding `i18n.changeLanguage(options.locale);`  in repo-header-labels\view.tsx enough to fix this?

2024-06-28 14:09 UTC, wxharry requested changes

2024-06-28 14:48 UTC, wxharry commented
> now it can display the corresponding language correctly under different language settings. However, this cannot take effect as soon as changing the language settings. It will only display the correct language **after refreshing the webpage**, unlike the star-button and the fork-button. 
> I think the reason for this is the repo-head-labels only be loaded once when initing the webpage, so the change of language setting will not take effect immediately since the repo-head-labels won't be reloaded. Even if I change the code as follows (add the options.locale in ** **), it won't help for the same reason. (I’m not pretty sure about the reason).
> Since I'm not quite familiar with React, I don't know the exact reason for this and where to change to fix this problem. If you give me a more specific reason for the bug, I would like to try to fix the issue! 🧐 Or is the current solution as adding `i18n.changeLanguage(options.locale);` in repo-header-labels\view.tsx enough to fix this?

That is highly likely. Then I guess we can fix the issue essentially by extracting the tooltip chart out of the labels and injecting it to the labels same as other charts, so the labels and charts can have different injecting mechanism. This is not our focus in this pr, but could you look into it a bit deeper to see if your theory is correct? We can update anything related to that issue.(Of course, if you can fix it, that would be great! 😄  )

2024-06-29 04:40 UTC, taketaketakeru commented
> 
> That is highly likely. Then I guess we can fix the issue essentially by extracting the tooltip chart out of the labels and injecting it to the labels same as other charts, so the labels and charts can have different injecting mechanism. This is not our focus in this pr, but could you look into it a bit deeper to see if your theory is correct? We can update anything related to that issue.(Of course, if you can fix it, that would be great! 😄 )

Thank you for your advice! It feels like I know how to fix this bug! 😉 
I will try and see if I can fix it when I have time! If there is any progress, I will comment here. 🧐

2024-06-29 15:14 UTC, taketaketakeru commented
It seems I fix the #804 issue, even though I'm not sure if it is the simplest way.

2024-06-29 15:15 UTC, taketaketakeru commented
> > That is highly likely. Then I guess we can fix the issue essentially by extracting the tooltip chart out of the labels and injecting it to the labels same as other charts, so the labels and charts can have different injecting mechanism. This is not our focus in this pr, but could you look into it a bit deeper to see if your theory is correct? We can update anything related to that issue.(Of course, if you can fix it, that would be great! 😄 )
> 
> Thank you for your advice! It feels like I know how to fix this bug! 😉 I will try and see if I can fix it when I have time! If there is any progress, I will comment here. 🧐

It seems I fixed the #804 issue, even though I'm not sure if it is the simplest way.

2024-06-29 15:20 UTC, taketaketakeru commented
> > That is highly likely. Then I guess we can fix the issue essentially by extracting the tooltip chart out of the labels and injecting it to the labels same as other charts, so the labels and charts can have different injecting mechanism. This is not our focus in this pr, but could you look into it a bit deeper to see if your theory is correct? We can update anything related to that issue.(Of course, if you can fix it, that would be great! 😄 )

It seems I fixed the #804 issue, even though I'm not sure if it is the simplest way. 🧐
Please look into it and let me know if there is any problem! 😄

2024-07-05 16:24 UTC, merged

2024-07-05 16:25 UTC, wxharry commented
Nice work! Thanks for your contributions! appreciate it.